# Generated by Django 4.0.4 on 2022-10-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='c',
            new_name='cluster',
        ),
    ]
