# Generated by Django 4.0.4 on 2022-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_c_farmer_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='rate',
        ),
        migrations.AddField(
            model_name='farmer',
            name='rate',
            field=models.ManyToManyField(to='accounts.rate'),
        ),
    ]
