# Generated by Django 4.0.4 on 2022-10-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rate_remove_farmer_rate_farmer_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(choices=[(1, '1-trash'), (2, '2-bad'), (3, '3-ok'), (4, '4-good'), (5, '5-very good')], default=0, null=True),
        ),
    ]
