# Generated by Django 4.0.4 on 2022-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_rate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='rate',
        ),
        migrations.AddField(
            model_name='farmer',
            name='rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
