# Generated by Django 4.0.4 on 2022-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_farmer_rate_farmer_rate_delete_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_rating',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
