# Generated by Django 4.0.4 on 2022-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_customer_price_customer_customer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
