# Generated by Django 4.0.4 on 2022-10-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_classificatoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='classificatoin',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
