# Generated by Django 4.0.4 on 2022-11-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_classificatoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='farmer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.farmer'),
        ),
    ]
